version: 2.1
orbs:
  architect: giantswarm/architect@5.6.0

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            tags:
              only: /^v.*/
