version: 2.1
orbs:
  architect: giantswarm/architect@5.11.0

jobs:
  tests:
    executor: architect/machine
    machine:
      image: default
    steps:
      - checkout
      - architect/machine-install-go
      - run:
          name: "Create cache dir"
          command: |
            sudo mkdir -p /golancilint-cache
            sudo chown -R $USER:$USER /golancilint-cache
      - architect/integration-test-install-tools:
          apptestctl-version: v0.14.1
          helm-version: v3.8.2
          kubernetes-version: v1.21.1
      - architect/go-cache-restore
      - run:
          name: "Install golang-lint"
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
            sudo cp $(go env GOPATH)/bin/golangci-lint /usr/local/bin/golangci-lint
      - run:
          name: "Install nancy"
          command: |
            curl -sSL -o nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.46/nancy-v1.0.46-linux-amd64
            chmod +x nancy
            sudo cp nancy /usr/local/bin/nancy
      - architect/go-test
      - architect/go-cache-save

workflows:
  test:
    jobs:
      - tests:
          filters:
            tags:
              only: /^v.*/
